channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.7.2=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.15=h5eee18b_0
  - python=3.11.9=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
    - absl-py==2.1.0
    - accelerate==1.1.1
    - addict==2.4.0
    - aiohappyeyeballs==2.4.4
    - aiohttp==3.11.9
    - aiosignal==1.3.1
    - annotated-types==0.7.0
    - anyio==4.6.2.post1
    - appdirs==1.4.4
    - argparse==1.4.0
    - arviz==0.20.0
    - astropy==6.1.4
    - astropy-iers-data==0.2024.11.4.0.33.34
    - attrs==24.2.0
    - beautifulsoup4==4.12.3
    - bibtexparser==1.4.3
    - biopython==1.84
    - blis==0.7.11
    - cachetools==5.5.0
    - catalogue==1.0.2
    - certifi==2024.8.30
    - cffi==1.17.1
    - charset-normalizer==3.3.2
    - chess==1.11.1
    - cirq==1.4.1
    - cirq-aqt==1.4.1
    - cirq-core==1.4.1
    - cirq-google==1.4.1
    - cirq-ionq==1.4.1
    - cirq-pasqal==1.4.1
    - cirq-rigetti==1.4.1
    - cirq-web==1.4.1
    - clarabel==0.9.0
    - click==8.1.7
    - cloudpathlib==0.19.0
    - cloudpickle==3.1.0
    - colorama==0.4.6
    - compressed-tensors==0.8.0
    - contourpy==1.3.0
    - cpm-kernels==1.0.11
    - cpmpy==0.9.23
    - cramjam==2.8.3
    - cryptography==43.0.3
    - cvxpy==1.5.3
    - cycler==0.12.1
    - cymem==2.0.8
    - datasets==3.1.0
    - deprecated==1.2.14
    - dill==0.3.8
    - diskcache==5.6.3
    - distro==1.9.0
    - docker-pycreds==0.4.0
    - docopt==0.6.2
    - duet==0.2.9
    - ecos==2.0.14
    - einops==0.5.0
    - en-core-web-sm==2.3.1
    - et-xmlfile==2.0.0
    - evalplus==0.1.0.dev598
    - evaluate==0.4.3
    - fastapi==0.115.5
    - fastparquet==2024.5.0
    - fastprogress==1.0.3
    - filelock==3.16.1
    - fire==0.7.0
    - fonttools==4.54.1
    - frozendict==2.4.6
    - frozenlist==1.5.0
    - fsspec==2024.9.0
    - func-timeout==4.3.5
    - fuzzywuzzy==0.18.0
    - gguf==0.10.0
    - gitdb==4.0.11
    - gitpython==3.1.43
    - gmpy2==2.2.1
    - google-api-core==2.22.0
    - google-auth==2.35.0
    - googleapis-common-protos==1.65.0
    - greenlet==3.1.1
    - grilops==0.10.3
    - grpc-interceptor==0.15.4
    - grpcio==1.67.1
    - grpcio-status==1.62.3
    - h11==0.14.0
    - h5netcdf==1.4.0
    - h5py==3.12.1
    - html5lib==1.1
    - httpcore==1.0.6
    - httptools==0.6.4
    - httpx==0.27.2
    - huggingface-hub==0.24.7
    - idna==3.10
    - immutabledict==4.2.0
    - importlib-metadata==8.5.0
    - interegular==0.3.3
    - jieba==0.42.1
    - jinja2==3.1.4
    - jiter==0.8.0
    - joblib==1.4.2
    - json5==0.10.0
    - jsonschema==4.23.0
    - jsonschema-specifications==2024.10.1
    - kiwisolver==1.4.7
    - langcodes==3.4.0
    - language-data==1.2.0
    - lark==1.2.2
    - levenshtein==0.26.1
    - llvmlite==0.43.0
    - lm-format-enforcer==0.10.9
    - lxml==5.3.0
    - mando==0.7.1
    - marisa-trie==1.2.0
    - markdown==3.7
    - markdown-it-py==3.0.0
    - markupsafe==2.1.5
    - matplotlib==3.9.2
    - matplotlib-inline==0.1.7
    - mdurl==0.1.2
    - mistral-common==1.5.1
    - mistune==3.0.2
    - mmengine-lite==0.10.5
    - mosestokenizer==1.0.0
    - mpmath==1.3.0
    - msgpack==1.1.0
    - msgspec==0.18.6
    - multidict==6.1.0
    - multipledispatch==1.0.0
    - multiprocess==0.70.16
    - multitasking==0.0.11
    - murmurhash==1.0.10
    - nest-asyncio==1.6.0
    - networkx==3.4.1
    - nltk==3.8
    - numba==0.60.0
    - numpoly==1.2.14
    - numpy==1.26.4
    - openai==1.55.3
    - opencc==1.1.9
    - opencv-python-headless==4.10.0.84
    - openfile==0.0.7
    - openpyxl==3.1.5
    - ortools==9.9.3963
    - osqp==0.6.7.post3
    - outlines==0.0.46
    - packaging==23.2
    - pandas>=2.0.0
    - partial-json-parser==0.2.1.1.post4
    - patsy==0.5.6
    - peewee==3.17.7
    - pillow==10.4.0
    - pip==24.2
    - plac==1.1.3
    - platformdirs==4.3.6
    - playwright==1.49.1
    - poetry-core==1.9.0
    - portalocker==3.0.0
    - preshed==3.0.9
    - prettytable==3.12.0
    - prometheus-client==0.21.0
    - prometheus-fastapi-instrumentator==7.0.0
    - propcache==0.2.1
    - proto-plus==1.25.0
    - protobuf==4.25.5
    - psutil==6.1.0
    - pulp==2.9.0
    - py-cpuinfo==9.0.0
    - pyairports==2.1.1
    - pyarrow==17.0.0
    - pyasn1==0.6.1
    - pyasn1-modules==0.4.1
    - pycosat==0.6.6
    - pycountry==24.6.1
    - pycparser==2.22
    - pycryptodome==3.21.0
    - pydantic==2.9.2
    - pydantic-core==2.23.4
    - pyee==12.0.0
    - pyenchant==3.2.2
    - pyerfa==2.0.1.4
    - pyext==0.5
    - pygments==2.18.0
    - pymc3==3.11.4
    - pympler==1.1
    - pyparsing==3.2.0
    - pyperclip==1.9.0
    - pyquil==4.14.3
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.0.1
    - python-levenshtein==0.26.1
    - python-rapidjson==1.20
    - pytz==2024.2
    - pywavelets==1.7.0
    - pyyaml==6.0.2
    - pyzmq==26.2.0
    - qcs-api-client-common==0.10.0
    - qcs-sdk-python==0.20.1
    - qdldl==0.1.7.post4
    - quil==0.13.1
    - radon==6.0.1
    - rank-bm25==0.2.2
    - rapidfuzz==3.10.1
    - ray==2.39.0
    - referencing==0.35.1
    - regex==2024.9.11
    - requests==2.32.3
    - retrying==1.3.4
    - rich==13.8.1
    - rouge==1.0.1
    - rouge-chinese==1.0.3
    - rouge-score==0.1.2
    - rpcq==3.11.0
    - rpds-py==0.21.0
    - rsa==4.9
    - ruamel-yaml==0.18.6
    - ruamel-yaml-clib==0.2.12
    - sacrebleu==2.4.3
    - safetensors==0.4.5
    - scikit-learn==1.5.0
    - scipy==1.14.1
    - scs==3.2.7
    - seaborn==0.13.2
    - semver==3.0.2
    - sentence-transformers==2.2.2
    - sentencepiece==0.2.0
    - sentry-sdk==2.18.0
    - setproctitle==1.3.3
    - setuptools==72.1.0
    - shellingham==1.5.4
    - shortuuid==1.0.13
    - six==1.16.0
    - smart-open==7.0.4
    - smmap==5.0.1
    - sniffio==1.3.1
    - sortedcontainers==2.4.0
    - soupsieve==2.6
    - spacy==2.3.9
    - spacy-legacy==3.0.12
    - spacy-loggers==1.0.5
    - srsly==1.0.7
    - starlette==0.41.3
    - strip-markdown==1.3
    - sympy==1.13.1
    - tabulate==0.9.0
    - tempdir==0.7.1
    - termcolor==2.5.0
    - theano-pymc==1.1.2
    - thinc==7.4.6
    - threadpoolctl==3.5.0
    - tiktoken==0.7.0
    - timeout-decorator==0.5.0
    - tokenizers==0.20.3
    - toolwrapper==2.1.0
    - torch==2.5.1
    - torchvision==0.20.1
    - tqdm==4.66.5
    - traitlets==5.14.3
    - transformers==4.46.2
    - triton==3.1.0
    - typer==0.12.5
    - types-deprecated==1.2.9.20240311
    - typing-extensions==4.12.2
    - tzdata==2024.1
    - urllib3==2.2.3
    - uvicorn==0.32.1
    - uvloop==0.21.0
    - wandb==0.18.7
    - wasabi==0.10.1
    - watchfiles==1.0.0
    - wcwidth==0.2.13
    - webencodings==0.5.1
    - websockets==14.1
    - wget==3.2
    - wheel==0.43.0
    - wrapt==1.16.0
    - xarray==2024.10.0
    - xarray-einstats==0.8.0
    - xformers==0.0.28.post3
    - xxhash==3.5.0
    - yapf==0.43.0
    - yarl==1.18.3
    - yfinance==0.2.48
    - z3-solver==4.13.3.0
    - zipp==3.20.2
